export default actionTypes = {
  RESET_USER_PROFILE_STATE: 'RESET_USER_PROFILE_STATE',
  // RESET_FLASHCARDS_STATE: 'RESET_FLASHCARDS_STATE',
  RESET_USER_COLLECTIONS_STATE: 'RESET_USER_COLLECTIONS_STATE',

  // --- USER PROFILE ---
  UPSERT_USER_PROFILE: 'UPSERT_USER_PROFILE',
  UPSERT_USER_PROFILE_PENDING: 'UPSERT_USER_PROFILE_PENDING',
  UPSERT_USER_PROFILE_FULFILLED: 'UPSERT_USER_PROFILE_FULFILLED',
  UPSERT_USER_PROFILE_REJECTED: 'UPSERT_USER_PROFILE_REJECTED',

  FETCH_USER_PROFILE: 'FETCH_USER_PROFILE',
  FETCH_USER_PROFILE_PENDING: 'FETCH_USER_PROFILE_PENDING',
  FETCH_USER_PROFILE_FULFILLED: 'FETCH_USER_PROFILE_FULFILLED',
  FETCH_USER_PROFILE_REJECTED: 'FETCH_USER_PROFILE_REJECTED',

  // // --- FLASHCARDS ---
  // // FETCH_FLASHCARD_IDS: 'FETCH_FLASHCARD_IDS',
  // // FETCH_FLASHCARD_IDS_PENDING: 'FETCH_FLASHCARD_IDS_PENDING',
  // // FETCH_FLASHCARD_IDS_FULFILLED: 'FETCH_FLASHCARD_IDS_FULFILLED',
  // // FETCH_FLASHCARD_IDS_REJECTED: 'FETCH_FLASHCARD_IDS_REJECTED',
  //
  // FETCH_FLASHCARD: 'FETCH_FLASHCARD',
  // FETCH_FLASHCARD_PENDING: 'FETCH_FLASHCARD_PENDING',
  // FETCH_FLASHCARD_FULFILLED: 'FETCH_FLASHCARD_FULFILLED',
  // FETCH_FLASHCARD_REJECTED: 'FETCH_FLASHCARD_REJECTED',
  //
  // FETCH_FLASHCARDS: 'FETCH_FLASHCARDS',
  // FETCH_FLASHCARDS_PENDING: 'FETCH_FLASHCARDS_PENDING',
  // FETCH_FLASHCARDS_FULFILLED: 'FETCH_FLASHCARDS_FULFILLED',
  // FETCH_FLASHCARDS_REJECTED: 'FETCH_FLASHCARDS_REJECTED',
  //
  // FETCH_FLASHCARDS_WITH_TAGS: 'FETCH_FLASHCARDS_WITH_TAGS',
  // FETCH_FLASHCARDS_WITH_TAGS_PENDING: 'FETCH_FLASHCARDS_WITH_TAGS_PENDING',
  // FETCH_FLASHCARDS_WITH_TAGS_FULFILLED: 'FETCH_FLASHCARDS_WITH_TAGS_FULFILLED',
  // FETCH_FLASHCARDS_WITH_TAGS_REJECTED: 'FETCH_FLASHCARDS_WITH_TAGS_REJECTED',

  // --- COLLECTIONS ---
  // FETCH_COLLECTIONS: 'FETCH_COLLECTIONS',
  // FETCH_COLLECTIONS_PENDING: 'FETCH_COLLECTIONS_PENDING',
  // FETCH_COLLECTIONS_FULFILLED: 'FETCH_COLLECTIONS_FULFILLED',
  // FETCH_COLLECTIONS_REJECTED: 'FETCH_COLLECTIONS_REJECTED',
  //
  // // CREATE_COLLECTION: 'CREATE_COLLECTION',
  // // CREATE_COLLECTION_PENDING: 'CREATE_COLLECTION_PENDING',
  // // CREATE_COLLECTION_FULFILLED: 'CREATE_COLLECTION_FULFILLED',
  // // CREATE_COLLECTION_REJECTED: 'CREATE_COLLECTION_REJECTED',
  // //
  // // FETCH_COLLECTION: 'FETCH_COLLECTION',
  // // FETCH_COLLECTION_PENDING: 'FETCH_COLLECTION_PENDING',
  // // FETCH_COLLECTION_FULFILLED: 'FETCH_COLLECTION_FULFILLED',
  // // FETCH_COLLECTION_REJECTED: 'FETCH_COLLECTION_REJECTED',
  // //
  // // UPDATE_COLLECTION: 'UPDATE_COLLECTION',
  // // UPDATE_COLLECTION_PENDING: 'UPDATE_COLLECTION_PENDING',
  // // UPDATE_COLLECTION_FULFILLED: 'UPDATE_COLLECTION_FULFILLED',
  // // UPDATE_COLLECTION_REJECTED: 'UPDATE_COLLECTION_REJECTED',
  // //
  // // DELETE_COLLECTION: 'DELETE_COLLECTION',
  // // DELETE_COLLECTION_PENDING: 'DELETE_COLLECTION_PENDING',
  // // DELETE_COLLECTION_FULFILLED: 'DELETE_COLLECTION_FULFILLED',
  // // DELETE_COLLECTION_REJECTED: 'DELETE_COLLECTION_REJECTED',
  // //
  // // STARRED_USER_COLLECTION_ON: 'STARRED_USER_COLLECTION_ON',
  // // STARRED_USER_COLLECTION_UPDATED: 'STARRED_USER_COLLECTION_UPDATED',
  // // STARRED_USER_COLLECTION_OFF: 'STARRED_USER_COLLECTION_OFF',
  
  // --- USER PREFS ---
  // FETCH_USER_FLASHCARD_PREFS: 'FETCH_USER_FLASHCARD_PREFS',
  // FETCH_USER_FLASHCARD_PREFS_PENDING: 'FETCH_USER_FLASHCARD_PREFS_PENDING',
  // FETCH_USER_FLASHCARD_PREFS_FULFILLED: 'FETCH_USER_FLASHCARD_PREFS_FULFILLED',
  // FETCH_USER_FLASHCARD_PREFS_REJECTED: 'FETCH_USER_FLASHCARD_PREFS_REJECTED',

  UPDATE_USER_FLASHCARD_PREFS: 'UPDATE_USER_FLASHCARD_PREFS',
  UPDATE_USER_FLASHCARD_PREFS_PENDING: 'UPDATE_USER_FLASHCARD_PREFS_PENDING',
  UPDATE_USER_FLASHCARD_PREFS_FULFILLED: 'UPDATE_USER_FLASHCARD_PREFS_FULFILLED',
  UPDATE_USER_FLASHCARD_PREFS_REJECTED: 'UPDATE_USER_FLASHCARD_PREFS_REJECTED',

  UPDATE_USER_COLLECTION_PREFS: 'UPDATE_USER_COLLECTION_PREFS',
  UPDATE_USER_COLLECTION_PREFS_PENDING: 'UPDATE_USER_COLLECTION_PREFS_PENDING',
  UPDATE_USER_COLLECTION_PREFS_FULFILLED: 'UPDATE_USER_COLLECTION_PREFS_FULFILLED',
  UPDATE_USER_COLLECTION_PREFS_REJECTED: 'UPDATE_USER_COLLECTION_PREFS_REJECTED',

  SUBMIT_FEEDBACK: 'SUBMIT_FEEDBACK',
  SUBMIT_FEEDBACK_PENDING: 'SUBMIT_FEEDBACK_PENDING',
  SUBMIT_FEEDBACK_FULFILLED: 'SUBMIT_FEEDBACK_FULFILLED',
  SUBMIT_FEEDBACK_REJECTED: 'SUBMIT_FEEDBACK_REJECTED',
}
