export default actionTypes = {
  RESET_USER_COLLECTIONS_STATE: 'RESET_USER_COLLECTIONS_STATE',

  // --- COLLECTIONS ---
  FETCH_COLLECTIONS: 'FETCH_COLLECTIONS',
  FETCH_COLLECTIONS_PENDING: 'FETCH_COLLECTIONS_PENDING',
  FETCH_COLLECTIONS_FULFILLED: 'FETCH_COLLECTIONS_FULFILLED',
  FETCH_COLLECTIONS_REJECTED: 'FETCH_COLLECTIONS_REJECTED',

  // CREATE_COLLECTION: 'CREATE_COLLECTION',
  // CREATE_COLLECTION_PENDING: 'CREATE_COLLECTION_PENDING',
  // CREATE_COLLECTION_FULFILLED: 'CREATE_COLLECTION_FULFILLED',
  // CREATE_COLLECTION_REJECTED: 'CREATE_COLLECTION_REJECTED',
  //
  // FETCH_COLLECTION: 'FETCH_COLLECTION',
  // FETCH_COLLECTION_PENDING: 'FETCH_COLLECTION_PENDING',
  // FETCH_COLLECTION_FULFILLED: 'FETCH_COLLECTION_FULFILLED',
  // FETCH_COLLECTION_REJECTED: 'FETCH_COLLECTION_REJECTED',
  //
  // UPDATE_COLLECTION: 'UPDATE_COLLECTION',
  // UPDATE_COLLECTION_PENDING: 'UPDATE_COLLECTION_PENDING',
  // UPDATE_COLLECTION_FULFILLED: 'UPDATE_COLLECTION_FULFILLED',
  // UPDATE_COLLECTION_REJECTED: 'UPDATE_COLLECTION_REJECTED',
  //
  // DELETE_COLLECTION: 'DELETE_COLLECTION',
  // DELETE_COLLECTION_PENDING: 'DELETE_COLLECTION_PENDING',
  // DELETE_COLLECTION_FULFILLED: 'DELETE_COLLECTION_FULFILLED',
  // DELETE_COLLECTION_REJECTED: 'DELETE_COLLECTION_REJECTED',
  //
  // STARRED_USER_COLLECTION_ON: 'STARRED_USER_COLLECTION_ON',
  // STARRED_USER_COLLECTION_UPDATED: 'STARRED_USER_COLLECTION_UPDATED',
  // STARRED_USER_COLLECTION_OFF: 'STARRED_USER_COLLECTION_OFF',
}
