export default actionTypes = {
  RESET_USER_PROFILE_STATE: 'RESET_USER_PROFILE_STATE',

  FETCH_USER_PROFILE: 'FETCH_USER_PROFILE',
  FETCH_USER_PROFILE_PENDING: 'FETCH_USER_PROFILE_PENDING',
  FETCH_USER_PROFILE_FULFILLED: 'FETCH_USER_PROFILE_FULFILLED',
  FETCH_USER_PROFILE_REJECTED: 'FETCH_USER_PROFILE_REJECTED',

  UPSERT_USER_PROFILE: 'UPSERT_USER_PROFILE',
  UPSERT_USER_PROFILE_PENDING: 'UPSERT_USER_PROFILE_PENDING',
  UPSERT_USER_PROFILE_FULFILLED: 'UPSERT_USER_PROFILE_FULFILLED',
  UPSERT_USER_PROFILE_REJECTED: 'UPSERT_USER_PROFILE_REJECTED',

  UPSERT_USER_PURCHASES: 'UPSERT_USER_PURCHASES',
  UPSERT_USER_PURCHASES_PENDING: 'UPSERT_USER_PURCHASES_PENDING',
  UPSERT_USER_PURCHASES_FULFILLED: 'UPSERT_USER_PURCHASES_FULFILLED',
  UPSERT_USER_PURCHASES_REJECTED: 'UPSERT_USER_PURCHASES_REJECTED',
}
