export default actionTypes = {
  // --- USER PREFS ---
  // FETCH_USER_FLASHCARD_PREFS: 'FETCH_USER_FLASHCARD_PREFS',
  // FETCH_USER_FLASHCARD_PREFS_PENDING: 'FETCH_USER_FLASHCARD_PREFS_PENDING',
  // FETCH_USER_FLASHCARD_PREFS_FULFILLED: 'FETCH_USER_FLASHCARD_PREFS_FULFILLED',
  // FETCH_USER_FLASHCARD_PREFS_REJECTED: 'FETCH_USER_FLASHCARD_PREFS_REJECTED',

  UPDATE_USER_FLASHCARD_PREFS: 'UPDATE_USER_FLASHCARD_PREFS',
  UPDATE_USER_FLASHCARD_PREFS_PENDING: 'UPDATE_USER_FLASHCARD_PREFS_PENDING',
  UPDATE_USER_FLASHCARD_PREFS_FULFILLED: 'UPDATE_USER_FLASHCARD_PREFS_FULFILLED',
  UPDATE_USER_FLASHCARD_PREFS_REJECTED: 'UPDATE_USER_FLASHCARD_PREFS_REJECTED',

  UPDATE_USER_COLLECTION_PREFS: 'UPDATE_USER_COLLECTION_PREFS',
  UPDATE_USER_COLLECTION_PREFS_PENDING: 'UPDATE_USER_COLLECTION_PREFS_PENDING',
  UPDATE_USER_COLLECTION_PREFS_FULFILLED: 'UPDATE_USER_COLLECTION_PREFS_FULFILLED',
  UPDATE_USER_COLLECTION_PREFS_REJECTED: 'UPDATE_USER_COLLECTION_PREFS_REJECTED',
}
