export default actionTypes = {
  FETCH_USER_COUNTERS: 'FETCH_USER_COUNTERS',
  FETCH_USER_COUNTERS_PENDING: 'FETCH_USER_COUNTERS_PENDING',
  FETCH_USER_COUNTERS_FULFILLED: 'FETCH_USER_COUNTERS_FULFILLED',
  FETCH_USER_COUNTERS_REJECTED: 'FETCH_USER_COUNTERS_REJECTED',

  INCREMENT_USER_SESSIONS_COUNTER: 'INCREMENT_USER_SESSIONS_COUNTER',
  INCREMENT_USER_SESSIONS_COUNTER_PENDING: 'INCREMENT_USER_SESSIONS_COUNTER_PENDING',
  INCREMENT_USER_SESSIONS_COUNTER_FULFILLED: 'INCREMENT_USER_SESSIONS_COUNTER_FULFILLED',
  INCREMENT_USER_SESSIONS_COUNTER_REJECTED: 'INCREMENT_USER_SESSIONS_COUNTER_REJECTED',

  INCREMENT_USER_ACTIONS_COUNTER: 'INCREMENT_USER_ACTIONS_COUNTER',
  INCREMENT_USER_ACTIONS_COUNTER_PENDING: 'INCREMENT_USER_ACTIONS_COUNTER_PENDING',
  INCREMENT_USER_ACTIONS_COUNTER_FULFILLED: 'INCREMENT_USER_ACTIONS_COUNTER_FULFILLED',
  INCREMENT_USER_ACTIONS_COUNTER_REJECTED: 'INCREMENT_USER_ACTIONS_COUNTER_REJECTED',

  UPSERT_USER_PROMPT_COUNTERS: 'UPSERT_USER_PROMPT_COUNTERS',
  UPSERT_USER_PROMPT_COUNTERS_PENDING: 'UPSERT_USER_PROMPT_COUNTERS_PENDING',
  UPSERT_USER_PROMPT_COUNTERS_FULFILLED: 'UPSERT_USER_PROMPT_COUNTERS_FULFILLED',
  UPSERT_USER_PROMPT_COUNTERS_REJECTED: 'UPSERT_USER_PROMPT_COUNTERS_REJECTED',
}
