const C = {
  WSET_2: 'WSET_2',
  WSET_3: 'WSET_3',
  TAB_ICON_SIZE: 32,

  PUSH_ROUTE: 'PUSH_ROUTE',
  POP_ROUTE: 'POP_ROUTE',

  STUDY_HOME: 'STUDY_HOME',
  STUDY_SECTION: 'STUDY_SECTION',
  STUDY_FLASHCARDS: 'STUDY_FLASHCARDS',

  SIDE_FRONT: 'SIDE_FRONT',
  SIDE_BACK: 'SIDE_BACK'
}

export default C;
