const C = {
  // STATE
  S_GLOBAL_NAV: 'STATE_GLOBAL_NAV',
  S_APPTABS_NAV: 'STATE_APPTABS_NAV',
  S_STUDYTAB_NAV: 'STATE_STUDYTAB_NAV',
  S_STUDYTAB: 'STATE_STUDYTAB',

  // CONFIG state consts
  WSET_2: 'WSET_2',
  WSET_3: 'WSET_3',
  TAB_ICON_SIZE: 32,

  // NAVIGATION state consts
  PUSH_ROUTE: 'PUSH_ROUTE',
  POP_ROUTE: 'POP_ROUTE',

  STUDY_HOME: 'STUDY_HOME',
  STUDY_SECTION: 'STUDY_SECTION',
  STUDY_FLASHCARDS: 'STUDY_FLASHCARDS',

  CARD_FRONT: 'CARD_FRONT',
  CARD_BACK: 'CARD_BACK',

  // USER state consts
  U_LOGGED_IN: 'USER_LOGGED_IN',
  U_LOGGED_OUT: 'USER_LOGGED_OUT',
  U_PERMA_BAN: 'USER_PERMA_BAN',
  U_TEMP_BAN: 'USER_TEMP_BAN',
  U_ACTIVE: 'USER_ACTIVE',
  U_INACTIVE: 'USER_INACTIVE',

  // NETWORK state consts
  INVALIDATE_SECTION_DECKS: 'INVALIDATE_SECTION_DECKS',
  REQUEST_SECTION_DECKS: 'REQUEST_SECTION_DECKS',
  RECEIVE_SECTION_DECKS: 'RECEIVE_SECTION_DECKS',
}

export default C;
