export default events = {
  firebase_error: 'firebase_error',
  // user_actions: 'user_actions',
  auth_signin_bounce: 'auth_signin_bounce',
  auth_signup_bounce: 'auth_signup_bounce',
  auth_signing_in: 'auth_signing_in',
  auth_signed_in: 'auth_signed_in',
  auth_signed_out: 'auth_signed_out',
  auth_signed_up: 'auth_signed_up',
  auth_signin_error: 'auth_signin_error',
  auth_reset_password: 'auth_reset_password',
  // event_configure_set: 'configure_set',
  // event_configure_set_saved: 'configure_set_saved',
  // event_configure_set_deleted: 'configure_set_deleted',
  // event_configure_set_aborted: 'configure_set_aborted',
  view_set: 'view_set',
  view_set_aborted: 'view_set_aborted',
  view_set_completed: 'view_set_completed',
  collection_type_featured: 'collection_type_featured',
  collection_type_bookmarked: 'collection_type_bookmarked',
  collection_type_starred: 'collection_type_starred',
  // collection_type_user: 'collection_type_user',
  update_flashcard_pref: 'update_flashcard_pref',
  update_collection_pref: 'update_collection_pref',
}
