export default routes = {
  NAV_USER_SIGNIN: 'NAV_USER_SIGNIN',
  NAV_HOME_TAB: 'NAV_HOME_TAB',
  NAV_COLLECTIONS_TAB: 'NAV_COLLECTIONS_TAB',
  NAV_STARRED_TAB: 'NAV_STARRED_TAB',
  NAV_PROFILE_TAB: 'NAV_PROFILE_TAB',
  NAV_SEARCH_TAB: 'NAV_SEARCH_TAB',

  NAV_FLASHCARDS_SET_CONFIGURATOR: 'NAV_FLASHCARDS_SET_CONFIGURATOR',

  NAV_HOME: 'NAV_HOME',
  NAV_HOME_FLASHCARDS_VIEWER: 'NAV_HOME_FLASHCARDS_VIEWER',
  NAV_COLLECTIONS_HOME: 'NAV_COLLECTIONS_HOME',
  NAV_COLLECTIONS_FLASHCARDS_VIEWER: 'NAV_COLLECTIONS_FLASHCARDS_VIEWER',
  NAV_STARRED_HOME: 'NAV_STARRED_HOME',
  NAV_STARRED_FILTER_CONFIGURATOR: 'NAV_STARRED_FILTER_CONFIGURATOR',
  NAV_SEARCH_HOME: 'NAV_SEARCH_HOME',
  NAV_SEARCH_RESULTS: 'NAV_SEARCH_RESULTS',
  NAV_USER_SIGNIN_HOME: 'NAV_USER_SIGNIN_HOME',
  NAV_USER_SIGNIN_WITH_EMAIL: 'NAV_USER_SIGNIN_WITH_EMAIL',
  NAV_USER_SIGNUP_WITH_EMAIL: 'NAV_USER_SIGNUP_WITH_EMAIL',
  NAV_USER_PROFILE_HOME: 'NAV_USER_PROFILE_HOME',
  NAV_USER_PROFILE_SEND_FEEDBACK: 'NAV_USER_PROFILE_SEND_FEEDBACK',
  NAV_ABOUT_HOME: 'NAV_ABOUT_HOME',

  NAV_ABOUT_APP_ICONS: 'NAV_ABOUT_APP_ICONS',
}
