export default actionTypes = {
  FEEDBACK_SUBMIT: 'FEEDBACK_SUBMIT',
  FEEDBACK_SUBMIT_PENDING: 'FEEDBACK_SUBMIT_PENDING',
  FEEDBACK_SUBMIT_FULFILLED: 'FEEDBACK_SUBMIT_FULFILLED',
  FEEDBACK_SUBMIT_REJECTED: 'FEEDBACK_SUBMIT_REJECTED',
}
