export default actionTypes = {
  RESET_FLASHCARDS_STATE: 'RESET_FLASHCARDS_STATE',

  // --- FLASHCARDS ---
  // FETCH_FLASHCARD_IDS: 'FETCH_FLASHCARD_IDS',
  // FETCH_FLASHCARD_IDS_PENDING: 'FETCH_FLASHCARD_IDS_PENDING',
  // FETCH_FLASHCARD_IDS_FULFILLED: 'FETCH_FLASHCARD_IDS_FULFILLED',
  // FETCH_FLASHCARD_IDS_REJECTED: 'FETCH_FLASHCARD_IDS_REJECTED',

  FETCH_FLASHCARD: 'FETCH_FLASHCARD',
  FETCH_FLASHCARD_PENDING: 'FETCH_FLASHCARD_PENDING',
  FETCH_FLASHCARD_FULFILLED: 'FETCH_FLASHCARD_FULFILLED',
  FETCH_FLASHCARD_REJECTED: 'FETCH_FLASHCARD_REJECTED',

  FETCH_FLASHCARDS: 'FETCH_FLASHCARDS',
  FETCH_FLASHCARDS_PENDING: 'FETCH_FLASHCARDS_PENDING',
  FETCH_FLASHCARDS_FULFILLED: 'FETCH_FLASHCARDS_FULFILLED',
  FETCH_FLASHCARDS_REJECTED: 'FETCH_FLASHCARDS_REJECTED',

  FETCH_FLASHCARDS_WITH_TAGS: 'FETCH_FLASHCARDS_WITH_TAGS',
  FETCH_FLASHCARDS_WITH_TAGS_PENDING: 'FETCH_FLASHCARDS_WITH_TAGS_PENDING',
  FETCH_FLASHCARDS_WITH_TAGS_FULFILLED: 'FETCH_FLASHCARDS_WITH_TAGS_FULFILLED',
  FETCH_FLASHCARDS_WITH_TAGS_REJECTED: 'FETCH_FLASHCARDS_WITH_TAGS_REJECTED',
}
