export default {
  NAV_HOME: 'NAV_HOME',
  NAV_HOME_DETAILED: 'NAV_HOME_DETAILED',
  NAV_BOOKMARKS_HOME: 'NAV_BOOKMARKS_HOME',
  NAV_BOOKMARKS_DETAILED: 'NAV_BOOKMARKS_DETAILED',
  NAV_SEARCH_HOME: 'NAV_SEARCH_HOME',
  NAV_SEARCH_RESULTS: 'NAV_SEARCH_RESULTS',
  NAV_PROFILE_HOME: 'NAV_PROFILE_HOME',
  NAV_PROFILE_DETAILED: 'NAV_PROFILE_DETAILED',
}
